name: Build Lina App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install PyInstaller
        run: pip install pyinstaller
      - name: Build EXE
        run: pyinstaller --onefile --windowed LinaApp_Kivy.py
      - name: Upload EXE
        uses: actions/upload-artifact@v3
        with:
          name: LinaApp-Windows
          path: dist/*.exe

  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y buildozer zip unzip openjdk-17-jdk
          pip install --upgrade buildozer cython
      - name: Init buildozer
        run: |
          buildozer init
          sed -i 's/main.py/LinaApp_Kivy.py/' buildozer.spec
      - name: Build APK
        run: buildozer android debug
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: LinaApp-Android
          path: bin/*.apk
